public with sharing class ConstantsHelper {
    public static final String AVAILABLE_STATUS = 'Available';
    public static final String IN_PROGRESS_STATUS = 'In Progress';
    public static final String COMPLETED_STATUS = 'Completed';
    public static final String FAILED_STATUS = 'Failed';
    public static final Integer MAX_MISSION_PER_USER = 3;
    public static final String SENDER_DISPLAY_NAME = 'Guild Master';
}